### PR TITLE
Support [FormControl] directive

### PR DESCRIPTION
**Pull request by ndcunningham**
(feat) - If a `[formControl]` directive is used the auto-complete control should still update it's value, and not be forced to use `formControlName` or the `form` tag.

fixes: #100

### CODE REVIEW

**Comment by allenhwkim** [comment]
@ndcunningham Do you need to update plunker example?

**Comment by ndcunningham** [comment]
You want a plnkr for it?

**Comment by allenhwkim** [comment]
We have an plunker example already as you seen in README.md
image

Do you need to update this to apply all your changes to users?

**Comment by ndcunningham** [comment]
I'll build one separately and update

**Comment by allenhwkim** [comment]
Thank you

**Comment by ndcunningham** [comment]
http://plnkr.co/edit/yCNNqBffko1VZFGpI2KU?p=preview @allenhwkim see the issue

**Comment by ndcunningham** [comment]
@allenhwkim when you merge i will update the `README.md`

**Comment by allenhwkim** [comment]
merged and released 0.8.9

**Pull request merged**
