### PR TITLE
fix #37, allow user input unless accept-user-input is 'false'

### LINKED ISSUE #37: Support to add entry even if its not present in source
not sure if its already possible, but would be awesome to have an option to enable input if its not part of the lookup source. (to add a new value)

### PR DESCRIPTION
**Pull request by allenhwkim**
fixes #37

### CODE REVIEW

**Comment by allenhwkim** [comment]
@boban984 could you review this?

**Comment by allenhwkim** [comment]
@bo

**Comment by allenhwkim** [comment]
@boban984 could you review this?

**Comment by allenhwkim** [comment]
@boban984 could you review this?

**Comment by Tanato** [comment]
Seems to me that you miss the emmit to ngModelChange

I've added the line below in your event 'componentInputChanged' and everything works well

    componentInputChanged = (val: string) => {
        if (this.acceptUserInput !== false) {
            this.inputEl.value = val;
            **(val !== this.ngModel) && this.ngModelChange.emit(val);**
        }
    };

**Pull request merged**
