### PR TITLE
proposing solution for request #28

### PR DESCRIPTION
**Pull request by seustachi**
This is a proposed solution for the issue : 
https://github.com/ng2-ui/ng2-auto-complete/issues/28

I implemented this to be able to bind what the user types, in order to be able to launch a search even if no result is matching.

### CODE REVIEW

**Comment by rajanya** [comment]
Hi..when is the merge happing?

**Comment by allenhwkim** [comment]
After reviewing this, I feel redundant between `inputChanged` and `valueChanged`.
I might be wrong though, @boban984 could you also review this change? We may not need to introduce another event.

**Comment by seustachi** [comment]
Hi Allen, 

I don't think this is redundant at all. CalueChanged is triggered when the user click on one of the proposed results.

What I try to achieve is the opposite : get the string typed even when there is no result found by the auto-complete.

The proposed solutions would not fit my use case.

To get an idea, twitter's autocomplete allows you to hit enter even if you type something that does not return any result.

**Comment by allenhwkim** [comment]
Thanks for  your input here, but I am really hesitant to introduce another event to user, which are already confusing with having two outputs. We currently have `ngModelChange` and `valueChanged`. Currently `valueChange` is an alias of `ngModelChange`. If I accept this merge we now have three, which will make users confused more.  I was almost close to remove `valueChanged` since it is the same as `ngModelChange`. 

I think we can still can make use of `valueChanged` to change the following line without introducing any other event. 

https://github.com/ng2-ui/ng2-auto-complete/blob/d26a7a5d3ef87205a7690bb114cf6d5b52542c47/src/auto-complete.component.ts#L227

What do you think about it?

**Comment by seustachi** [comment]
Indeed we need only 2 events. One for when the user picks a result in the list (`ngModelChange`) and one when the user is typing (could be `valueChanged`).

Then we would need to update the documentation, and I expect that some users will swaer because of the lack of backward compatibility, but on the long run it seems like a good renaming.

If you want I can modify my pull request in this direction. What do you think ?

**Comment by allenhwkim** [comment]
@seustachi `valueChanged` is used just in case users does not use `[(ngModel)]` at all. Without `[(ngModel)]`, it's not comfortable to us `ngModelChange`, so I left `valuleChanged` as it is.

What I don't know what you want to achieve is that, "when the user is typing..." part. Why do we need to know the selected value when they type? I think the value they type is just a temporary value to select a value. It's not a meaningful event for me.

After they type, and select something, then the `valueChanged` will be fired to user.

To satisfy your requirement, when they type `ENTER`, if none of items are selected, we can fire selectOne() with null value, which eventually will fire `valueChanged` to user like the following.

```
      case 13: // ENTER, choose it!!
        if (this.filteredList.length > 0) {
          this.selectOne(this.filteredList[this.itemIndex]);
        }  else if (this.filteredList.length === 0) {
          this.selectOne(null);
        }
        evt.preventDefault();
        break;
```

**Comment by rajanya** [comment]
@allenhwkim..I think the point that @seustachi wanted to emphasize is that even when user enters something which is not in the 'source', then also ngModel should hold the user entered data instead of null.

**Pull request closed without merging**
